#!/bin/bash
# A simple todo list using dmenu
TODO_FILE="$HOME/.todo"

# Create the file if does not exists
[ ! -f $TODO_FILE ] && touch $TODO_FILE

# Remove all empty lines from it
sed -ri '/^\s*$/d' $TODO_FILE

# Open the lines on dmenu and get the result from it
RESULT=`cat $TODO_FILE | dmenu -i -fn "Fira Code:size=12" -nb "#1b181b" -nf "#A3A3A3" -sb "#2EB398" -sf "#1b181b"`

# If nothing has been selected (user pressed ESC) just quit
[ -z "$RESULT" ] && exit

# Add to the list if it's a new todo, delete it otherwhise thisVallue
[ -z "`grep "$RESULT" $TODO_FILE`" ] && echo "$RESULT" >> $TODO_FILE || sed -i "/$RESULT/d" $TODO_FILE